# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: cgr.dev
  repository: defenseunicorns.com/valkey-iamguarded
  tag: v8.1.10

sentinel:
  image:  # Unicorn flavor option DNE
    registry: cgr.dev
    repository: defenseunicorns.com/valkey-sentinel-iamguarded
    tag: v8.1.10

metrics:
  image:
    registry: cgr.dev
    repository: defenseunicorns.com/prometheus-redis-exporter-iamguarded
    tag: v1.91.1
