# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: cgr.dev
  repository: du-uds-defenseunicorns/valkey
  tag: 8.0.1

sentinel:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/valkey-sentinel
    tag: 8.0.1

metrics:
  image:
    registry: cgr.dev
    repository: du-uds-defenseunicorns/prometheus-redis-exporter-bitnami
    tag: 1.65.0
