# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: docker.io
  repository: bitnami/valkey
  tag: 7.2.6-debian-12-r0

metrics:
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.62.0-debian-12-r2
