# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: docker.io
  repository: bitnami/valkey
  tag: 8.0.1-debian-12-r2

sentinel:
  image:
    registry: docker.io
    repository: bitnami/valkey-sentinel
    tag: 8.0.1-debian-12-r1

metrics:
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.65.0-debian-12-r2
