# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: docker.io
  repository: bitnami/valkey
  tag: 8.0.2-debian-12-r5

sentinel:
  image:
    registry: docker.io
    repository: bitnami/valkey-sentinel
    tag: 8.0.2-debian-12-r5

metrics:
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: 1.67.0-debian-12-r11
