# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

image:
  registry: docker.io
  repository: valkey/valkey
  tag: 8.1.3

sentinel:
  image:
    registry: docker.io
    repository: valkey/valkey
    tag: 8.1.3

metrics:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis-exporter
    tag: 1.76.0-debian-12-r0
