{{- $namespace := .Release.Namespace }}
{{- $existingSecret := lookup "v1" "Secret" $namespace "valkey-password" }}
{{- $password := (randAlphaNum 16) }}
{{- if $existingSecret }}
  {{- $decoded := index $existingSecret.data "valkey-password" | b64dec }}
  {{- $password = $decoded }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: valkey-password
  namespace: {{ $namespace }}
stringData:
  valkey-password: {{ $password | quote }}

{{- if .Values.copyPassword.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.copyPassword.secretName }}
  namespace: {{ .Values.copyPassword.namespace }}
stringData:
  {{- $data := dict .Values.copyPassword.secretKey $password }}
  {{- toYaml $data | nindent 2 }}
{{- end }}
