{{- $password := randAlphaNum 10 }}
apiVersion: v1
kind: Secret
metadata:
  name: valkey
  namespace: {{ .Release.Namespace }}
stringData:
  valkey-password: {{ printf "%s" $password | quote }}
{{- if .Values.copyPassword.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.copyPassword.secretName }}
  namespace: {{ .Values.copyPassword.namespace }}
stringData:
  {{ dict .Values.copyPassword.secretKey $password | toYaml }}
{{- end }}
