{{- if .Capabilities.APIVersions.Has "security.istio.io/v1beta1" }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: valkey-istio-exceptions
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app.kubernetes.io/instance: valkey
  portLevelMtls:
    "6379":
      mode: PERMISSIVE
{{- end }}
