# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

tasks:
  - name: all
    actions:
      - task: create-test-package
      - task: test-valkey

  - name: create-test-package
    description: Create the test package to confirm Valkey is working
    inputs:
      architecture:
        description: The architecture of the package to create
        default: ${UDS_ARCH}
    actions:
      - cmd: uds zarf package create tests --confirm --architecture="${{ .inputs.architecture }}" --skip-sbom

  - name: test-valkey
    actions:
      - description: Deploy the test package into the cluster
        cmd: uds zarf package deploy "zarf-package-valkey-test-${UDS_ARCH}-0.1.0.tar.zst" --confirm
