# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    # milestoned is added here as a way to retrigger workflows that are stuck or otherwise didn't run correctly
    types: [milestoned, opened, reopened, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.
  packages: read # Allows reading the content of the repository's packages.
  id-token: write
  pull-requests: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-flavor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: test-flavor
        uses: defenseunicorns/uds-common/.github/actions/test-flavor@7b90f661df51e2c60a9a3c0ae13fc710ebf6518d # v1.20.1
        id: test-flavor
    outputs:
      upgrade-flavors: ${{ steps.test-flavor.outputs.upgrade-flavors }}

  validate:
    needs: check-flavor
    strategy:
      fail-fast: true
      matrix:
        type: [install, upgrade]
        flavor: [upstream, unicorn]
    uses: defenseunicorns/uds-common/.github/workflows/callable-test.yaml@7b90f661df51e2c60a9a3c0ae13fc710ebf6518d # v1.20.1
    with:
      upgrade-flavors: ${{ needs.check-flavor.outputs.upgrade-flavors }}
      flavor: ${{ matrix.flavor }}
      type: ${{ matrix.type }}
      runsOn: uds-swf-ubuntu-big-boy-8-core
    secrets: inherit  # Inherits all secrets from the parent workflow.

  verify-test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Success
        run: echo "All tests passed successfully!"
